const colors = require('tailwindcss/colors')

module.exports = {
    content: [
        '../../plugins/*/*/blocks/*.block',
        './theme.yaml',
        './assets/src/js/**/*.{js,vue}',
        './blocks/**/*.block',
        './layouts/**/*.htm',
        './pages/**/*.htm',
        './partials/**/*.htm',
        './node_modules/flowbite/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                primary: 'var(--primary)',
                secondary: 'var(--secondary)',
                transparent: 'transparent',
                current: 'currentColor',
                black: colors.black,
                white: colors.white,
                slate: colors.slate,
                gray: colors.gray,
                zinc: colors.zinc,
                neutral: colors.neutral,
                stone: colors.stone,
                red: colors.red,
                orange: colors.orange,
                amber: colors.amber,
                yellow: colors.yellow,
                lime: colors.lime,
                green: colors.green,
                emerald: colors.emerald,
                teal: colors.teal,
                cyan: colors.cyan,
                sky: colors.sky,
                blue: colors.blue,
                indigo: colors.indigo,
                violet: colors.violet,
                purple: colors.purple,
                fuchsia: colors.fuchsia,
                pink: colors.pink,
                rose: colors.rose,
            },
            fontFamily: {
                standard: ['Roboto', 'sans-serif'],
                heading: ['Roboto', 'sans-serif'],
            },
            fontSize: {
                base: ['15.5px', '26px'],
                'base-mobile': ['14.5px', '23px'],
                'top-nav': ['13px', '18px'],
                'main-nav': ['18px', '24px'],
                heading: ['56px', '62px'],
                h1: ['44px', '48px'],
                h2: ['36px', '40px'],
                h3: ['28px', '34px'],
                h4: ['22px', '26px'],
                h5: ['18px', '24px'],
                h6: ['16px', '22px'],
                caption: ['14px', '22px'],
                'caption-mobile': ['13px', '20px'],
                disclaimer: ['13px', '20px'],
                'disclaimer-mobile': ['12px', '18px'],
                code: ['16px', '24px'],
                'code-mobile': ['15px', '22px'],
            },
            height: {
                '10vh': '10vh',
                '20vh': '20vh',
                '30vh': '30vh',
                '40vh': '40vh',
                '50vh': '50vh',
                '60vh': '60vh',
                '70vh': '70vh',
                '80vh': '80vh',
                '90vh': '90vh',
                '100vh': '100vh',
            },
            minHeight: {
                '10vh': '10vh',
                '20vh': '20vh',
                '30vh': '30vh',
                '40vh': '40vh',
                '50vh': '50vh',
                '60vh': '60vh',
                '70vh': '70vh',
                '80vh': '80vh',
                '90vh': '90vh',
                '100vh': '100vh',
            },
            letterSpacing: {
                tighter: '-.5px',
                tight: '-.25px',
                normal: '0',
                wide: '.25px',
                wider: '.5px',
            },
        },
    },
    darkMode: 'media',
    variants: {
        extend: {
            display: ['dark'],
        },
    },
    plugins: [
        require('flowbite/plugin')
    ],
}
