const colors = require('tailwindcss/colors')

module.exports = {
    content: [
        '../../plugins/*/*/blocks/*.block',
        './theme.yaml',
        './assets/src/js/**/*.{js,vue}',
        './blocks/**/*.block',
        './layouts/**/*.htm',
        './pages/**/*.htm',
        './partials/**/*.htm',
        './node_modules/flowbite/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                'base': 'var(--base)',
                'base-alt': 'var(--base-alt)',
                'base-content': 'var(--base-content)',
                'base-dark': 'var(--base-dark)',
                'base-dark-alt': 'var(--base-dark-alt)',
                'base-dark-content': 'var(--base-dark-content)',
                'nav': 'var(--nav)',
                'nav-content': 'var(--nav-content)',
                'nav-hover-content': 'var(--nav-hover-content)',
                'nav-focus-content': 'var(--nav-focus-content)',
                'nav-dark': 'var(--nav-dark)',
                'nav-dark-content': 'var(--nav-dark-content)',
                'nav-hover-dark-content': 'var(--nav-hover-dark-content)',
                'nav-focus-dark-content': 'var(--nav-focus-dark-content)',
                'nav-button-content': 'var(--nav-button-content)',
                'nav-button-hover': 'var(--nav-button-hover)',
                'nav-button-hover-content': 'var(--nav-button-hover-content)',
                'nav-button-focus': 'var(--nav-button-focus)',
                'nav-button-focus-content': 'var(--nav-button-focus-content)',
                'nav-button-dark-content': 'var(--nav-button-dark-content)',
                'nav-button-dark-hover': 'var(--nav-button-dark-hover)',
                'nav-button-dark-hover-content': 'var(--nav-button-dark-hover-content)',
                'nav-button-dark-focus': 'var(--nav-button-dark-focus)',
                'nav-button-dark-focus-content': 'var(--nav-button-dark-focus-content)',
                'sidenav': 'var(--sidenav)',
                'sidenav-content': 'var(--sidenav-content)',
                'sidenav-hover-content': 'var(--sidenav-hover-content)',
                'sidenav-focus-content': 'var(--sidenav-focus-content)',
                'sidenav-dark': 'var(--sidenav-dark)',
                'sidenav-dark-content': 'var(--sidenav-dark-content)',
                'sidenav-hover-dark-content': 'var(--sidenav-hover-dark-content)',
                'sidenav-focus-dark-content': 'var(--sidenav-focus-dark-content)',
                'sidenav-button-content': 'var(--sidenav-button-content)',
                'sidenav-button-hover': 'var(--sidenav-button-hover)',
                'sidenav-button-hover-content': 'var(--sidenav-button-hover-content)',
                'sidenav-button-focus': 'var(--sidenav-button-focus)',
                'sidenav-button-focus-content': 'var(--sidenav-button-focus-content)',
                'sidenav-button-dark-content': 'var(--sidenav-button-dark-content)',
                'sidenav-button-dark-hover': 'var(--sidenav-button-dark-hover)',
                'sidenav-button-dark-hover-content': 'var(--sidenav-button-dark-hover-content)',
                'sidenav-button-dark-focus': 'var(--sidenav-button-dark-focus)',
                'sidenav-button-dark-focus-content': 'var(--sidenav-button-dark-focus-content)',
                'footer': 'var(--footer)',
                'footer-content': 'var(--footer-content)',
                'footer-hover-content': 'var(--footer-hover-content)',
                'footer-focus-content': 'var(--footer-focus-content)',
                'footer-dark': 'var(--footer-dark)',
                'footer-dark-content': 'var(--footer-dark-content)',
                'footer-hover-dark-content': 'var(--footer-hover-dark-content)',
                'footer-focus-dark-content': 'var(--footer-focus-dark-content)',
                'copyright': 'var(--copyright)',
                'copyright-content': 'var(--copyright-content)',
                'copyright-hover-content': 'var(--copyright-hover-content)',
                'copyright-focus-content': 'var(--copyright-focus-content)',
                'copyright-dark': 'var(--copyright-dark)',
                'copyright-dark-content': 'var(--copyright-dark-content)',
                'copyright-hover-dark-content': 'var(--copyright-hover-dark-content)',
                'copyright-focus-dark-content': 'var(--copyright-focus-dark-content)',
                'primary': 'var(--primary)',
                'primary-content': 'var(--primary-content)',
                'primary-hover': 'var(--primary-hover)',
                'primary-hover-content': 'var(--primary-hover-content)',
                'primary-focus': 'var(--primary-focus)',
                'primary-focus-content': 'var(--primary-focus-content)',
                'primary-dark': 'var(--primary-dark)',
                'primary-dark-content': 'var(--primary-dark-content)',
                'primary-dark-hover': 'var(--primary-dark-hover)',
                'primary-dark-hover-content': 'var(--primary-dark-hover-content)',
                'primary-dark-focus': 'var(--primary-dark-focus)',
                'primary-dark-focus-content': 'var(--primary-dark-focus-content)',
                'secondary': 'var(--secondary)',
                'secondary-content': 'var(--secondary-content)',
                'secondary-hover': 'var(--secondary-hover)',
                'secondary-hover-content': 'var(--secondary-hover-content)',
                'secondary-focus': 'var(--secondary-focus)',
                'secondary-focus-content': 'var(--secondary-focus-content)',
                'secondary-dark': 'var(--secondary-dark)',
                'secondary-dark-content': 'var(--secondary-dark-content)',
                'secondary-dark-hover': 'var(--secondary-dark-hover)',
                'secondary-dark-hover-content': 'var(--secondary-dark-hover-content)',
                'secondary-dark-focus': 'var(--secondary-dark-focus)',
                'secondary-dark-focus-content': 'var(--secondary-dark-focus-content)',
                'accent': 'var(--accent)',
                'accent-content': 'var(--accent-content)',
                'accent-hover': 'var(--accent-hover)',
                'accent-hover-content': 'var(--accent-hover-content)',
                'accent-focus': 'var(--accent-focus)',
                'accent-focus-content': 'var(--accent-focus-content)',
                'accent-dark': 'var(--accent-dark)',
                'accent-dark-content': 'var(--accent-dark-content)',
                'accent-dark-hover': 'var(--accent-dark-hover)',
                'accent-dark-hover-content': 'var(--accent-dark-hover-content)',
                'accent-dark-focus': 'var(--accent-dark-focus)',
                'accent-dark-focus-content': 'var(--accent-dark-focus-content)',
                transparent: 'transparent',
                current: 'currentColor',
                black: colors.black,
                white: colors.white,
                slate: colors.slate,
                gray: colors.gray,
                zinc: colors.zinc,
                neutral: colors.neutral,
                stone: colors.stone,
                red: colors.red,
                orange: colors.orange,
                amber: colors.amber,
                yellow: colors.yellow,
                lime: colors.lime,
                green: colors.green,
                emerald: colors.emerald,
                teal: colors.teal,
                cyan: colors.cyan,
                sky: colors.sky,
                blue: colors.blue,
                indigo: colors.indigo,
                violet: colors.violet,
                purple: colors.purple,
                fuchsia: colors.fuchsia,
                pink: colors.pink,
                rose: colors.rose,
            },
            fontFamily: {
                standard: ['Roboto', 'sans-serif'],
                heading: ['Roboto', 'sans-serif'],
            },
            fontSize: {
                base: ['15.5px', '26px'],
                'base-mobile': ['14.5px', '23px'],
                'top-nav': ['13px', '18px'],
                'main-nav': ['18px', '24px'],
                heading: ['56px', '62px'],
                h1: ['44px', '48px'],
                h2: ['36px', '40px'],
                h3: ['28px', '34px'],
                h4: ['22px', '26px'],
                h5: ['18px', '24px'],
                h6: ['16px', '22px'],
                caption: ['14px', '22px'],
                'caption-mobile': ['13px', '20px'],
                disclaimer: ['13px', '20px'],
                'disclaimer-mobile': ['12px', '18px'],
                code: ['16px', '24px'],
                'code-mobile': ['15px', '22px'],
            },
            height: {
                '10vh': '10vh',
                '20vh': '20vh',
                '30vh': '30vh',
                '40vh': '40vh',
                '50vh': '50vh',
                '60vh': '60vh',
                '70vh': '70vh',
                '80vh': '80vh',
                '90vh': '90vh',
                '100vh': '100vh',
            },
            minHeight: {
                '10vh': '10vh',
                '20vh': '20vh',
                '30vh': '30vh',
                '40vh': '40vh',
                '50vh': '50vh',
                '60vh': '60vh',
                '70vh': '70vh',
                '80vh': '80vh',
                '90vh': '90vh',
                '100vh': '100vh',
            },
            letterSpacing: {
                tighter: '-.5px',
                tight: '-.25px',
                normal: '0',
                wide: '.25px',
                wider: '.5px',
            },
        },
    },
    darkMode: 'media',
    variants: {
        extend: {
            display: ['dark'],
        },
    },
    plugins: [
        require('flowbite/plugin')
    ],
}
